### ISSUE TITLE
Agent produces tree view instead of flamegraph

### ISSUE THREAD

**Issue by ennishol** [jvm-profiling-tools/ap-loader#10]
```jbang --javaagent=ap-loader@jvm-profiling-tools/ap-loader=start,event=cpu,file=profile.html jmh_example.java ```

When running the jbang example I've got html tree view instead of a flamegraph
```
Call tree view, total samples: 82
[0] 51.22% 42 self: 0.00% 0
start_thread
[0] 21.95% 18 self: 0.00% 0
red/hat/puzzles/loom/jmh_example.main
[0] 19.51% 16 self: 0.00% 0
org/openjdk/jmh/runner/link/BinaryLinkServer$Handler.run
[0] 3.66% 3 self: 0.00% 0
[unknown]
[0] 2.44% 2 self: 0.00% 0
__GI___pthread_cond_broadcast
[0] 1.22% 1 self: 0.00% 0
red/hat/puzzles/loom/jmh_example.<clinit>
```

Is this expected? If so, what is the option to get the flamegraph

**Comment by parttimenerd** [comment]
>  If so, what is the option to get the flamegraph

Have you tried passing the `flamegraph` option, i.e. `jbang --javaagent=ap-loader@jvm-profiling-tools/ap-loader=start,event=cpu,file=profile.html,flamegraph jmh_example.java`?

**Comment by ennishol** [comment]
Thanks, it generates a flame graph now. I thought it would be the default option.
Btw. there is a typo for jbang example. Instead of 
```jbang --javaagent:ap-loader@jvm-profiling-tools/ap-loader```
it should be
```jbang --javaagent=ap-loader@jvm-profiling-tools/ap-loader```

**Comment by parttimenerd** [comment]
Please open a PR for changes in the README, they are highly appreciated. Especially if you add text that would have prevented you from being confused :)
