### ISSUE TITLE
Replace or drop dev.dirs:directories due to licensing issues

### ISSUE THREAD

**Issue by jsjant** [jvm-profiling-tools/ap-loader#13]
This library uses Mozilla Public License 2.0. There are very subtle definitions on when you have to disclose your source and it's hard to use ap-loader due to this.

Would it be possible to replace this library with something like Files.createTempDirectory?

**Comment by parttimenerd** [comment]
I need this project at https://github.com/jvm-profiling-tools/ap-loader/blob/3f741ecaeb9a4abe2bc2e4ab50b130435ee96117/src/main/java/one/profiler/AsyncProfilerLoader.java#LL129C13-L129C13, to get the user data dir in which to store the extracted binaries in. This shouldn't be a temporary folder, as it has to persist after ap-loader exits. But we could of course use the fact that we're only supporting Linux and Mac OS and program it ourselves.

**Comment by parttimenerd** [comment]
We could probably implement it quite easily (using the information from the `dev.dirs:directories` README):

- Linux: " `$XDG_DATA_HOME` defines the base directory relative to which user-specific data files should be stored. If `$XDG_DATA_HOME` is either not set or empty, a default equal to `$HOME/.local/share` should be used." [freedesktop.org](https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html)
- MacOS: "Put app-created support files in the `Library/Application support/` directory. In general, this directory includes files that the app uses to run but that should remain hidden from the user. This directory can also include data files, configuration files, templates and modified versions of resources loaded from the app bundle." [Standard Directories](https://developer.apple.com/library/content/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/FileSystemOverview/FileSystemOverview.html#//apple_ref/doc/uid/TP40010672-CH2-SW6)

Do you want to implement this and remove the dependency?

**Comment by jsjant** [comment]
Yep, I'll try

**Comment by parttimenerd** [comment]
Fixed by the PR.

**Comment by jsjant** [comment]
Thank you!
