### ISSUE TITLE
Is it possible to support https://github.com/GoogleContainerTools/distroless? 

### ISSUE THREAD

**Issue by RoySunnySean007** [jvm-profiling-tools/ap-loader#15]
Dear ap-loader expert,

As we know, https://github.com/GoogleContainerTools/distroless doesn't contains shells, our ap-loader is a wrapper of async profiler which will execute the async profiler shell scripts (https://github.com/jvm-profiling-tools/ap-loader/blob/main/src/main/java/one/profiler/AsyncProfilerLoader.java#L598).
Is it possible to use jattach directly to support https://github.com/GoogleContainerTools/distroless? 

Thanks,
Roy

**Comment by parttimenerd** [comment]
`java -jar ap-loader.jar jattach` doesn't require a shell to run.

**Comment by RoySunnySean007** [comment]
Got it, thanks so much @parttimenerd !  Actually in most of cases, I need to use `java -jar ap-loader.jar profiler `, I will evaluate async profiler 2.10 as well.
