### ISSUE TITLE
Unknown argument: cpu

### ISSUE THREAD

**Issue by ennishol** [jvm-profiling-tools/ap-loader#21]
Used the README example and alloc and lock events are recorded but CPU is not

`java -jar ap-loader-all.jar profiler -e alloc,cpu,lock -d 60 -f all.jfr 79686
`
```
[WARN] Unknown argument: cpu
Profiling for 60 seconds
Done
```
```

ap-loader-all.jar version
3.0
```

**Comment by parttimenerd** [comment]
This is an issue of the underlying async-profiler.

**Comment by parttimenerd** [comment]
`java -jar ap-loader-all.jar profiler -e alloc -e cpu -e lock -d 60 -f all.jfr 79686` should work. Please file an issue with https://github.com/async-profiler/async-profiler.
