### ISSUE TITLE
Incorrect version in maven pom

### ISSUE THREAD

**Issue by gavlyukovskiy** [jvm-profiling-tools/ap-loader#3]
When trying to import ap-loader into gradle project
```
implementation("me.bechberger:ap-loader:2.9-all")
```
I'm getting
```
Execution failed for task ':project:compileKotlin'.
> Error while evaluating property 'filteredArgumentsMap' of task ':project:compileKotlin'.
   > Could not resolve all files for configuration ':project:compileClasspath'.
      > Could not resolve me.bechberger:ap-loader:2.9-all.
        Required by:
            project :project
         > Could not resolve me.bechberger:ap-loader:2.9-all.
            > inconsistent module metadata found. Descriptor: me.bechberger:ap-loader:2.8.3-all-SNAPSHOT Errors: bad version: expected='2.9-all' found='2.8.3-all-SNAPSHOT'
```
which seems to be because the pom has version 2.8.3-all-SNAPSHOT
https://repo1.maven.org/maven2/me/bechberger/ap-loader/2.9-all/ap-loader-2.9-all.pom

**Comment by parttimenerd** [comment]
Thanks for your bug report, I have a vague idea of how this came to be. I'll try to publish an updated version next week. You could use the snapshot version of 2.8.3 till then.

**Comment by parttimenerd** [comment]
I fixed the issue, please try using ap-loader again tomorrow, after the change is propagated to maven central.

```xml
<dependency>
  <groupId>me.bechberger</groupId>
  <artifactId>ap-loader</artifactId>
  <version>2.9-1-all</version>
</dependency>
```

**Comment by dpsoft** [comment]
Hi All! When trying to import ap-loader using the `2.9-1-all`  version into gradle project:

```
implementation("me.bechberger:ap-loader:2.9-1-all")
```

I'm getting this structure in the jar:

<img width="392" alt="image" src="https://user-images.githubusercontent.com/2567525/210009230-9e90c829-36d3-4b0d-909f-0aa7a4d1b7d4.png">

And this using `2.8.3-all-SNAPSHOT` version:

<img width="420" alt="image" src="https://user-images.githubusercontent.com/2567525/210009782-d656b6eb-ce72-4467-8cc0-2d77aade60d5.png">

this is ok?

**Comment by parttimenerd** [comment]
This should look different. I'm taking a look at it tomorrow. I'm sorry for the inconvenience.

**Comment by parttimenerd** [comment]
I'm currently working on the issue, sorry for the delay.

The built JARs themself look right, I'll have to investigate why there are problems publishing it.

**Comment by parttimenerd** [comment]
I can reproduce the problem: The published JARs differ from the built JARs (which I publish to the GitHub releases page).

**Comment by parttimenerd** [comment]
I fixed the issue (again), hopefully, it works now. The artifacts are in the snapshot repository and should appear on maven central in the next few hours:

```xml
<dependency>
  <groupId>me.bechberger</groupId>
  <artifactId>ap-loader</artifactId>
  <version>2.9-2-all</version>
</dependency>
```

**Comment by parttimenerd** [comment]
@dpsoft could you confirm that it is fixed?

**Comment by dpsoft** [comment]
Yes, thanks!

**Comment by parttimenerd** [comment]
Good, then I'll close this issue.
