### ISSUE TITLE
jbang enable ap-loader?

### ISSUE THREAD

**Issue by maxandersen** [jvm-profiling-tools/ap-loader#6]
ap-loader is awesome and I realized I can do this:

`jbang me.bechberger:ap-loader-all:LATEST`

Allowing you to use ap-loader  directly with no extra downloads (assuming you already have jbang)

without jbang it would be:

```
curl -Ls https://sh.jbang.dev | bash -s - me.bechberger:ap-loader-all:LATEST
```

In that spirit I was wondering if you would be up for adding a jvm-profiling-tools/jbang-catalog github repo or adding a jbang-catalog.json to this repo ?

it would allow to do:

`jbang ap-loader@jvm-profiling-tools` as a shorthand.

if inside this repo it would be `jbang ap-loader@jvm-profiling-tools/ap-loader` 

I can make PR's for both approaches but would need jbang-catalog repo to exist first if going for that option.

Can also just make update to the readme using the GAV approach (`jbang me.bechberger:ap-loader-all:LATEST`)

WDYT?

**Comment by maxandersen** [comment]
btw. due to #7 I suggest to use the github release URL instead then `jbang https://github.com/jvm-profiling-tools/ap-loader/releases/latest/download/ap-loader-all.jar` works.

I added ap-loader to https://github.com/maxandersen/jbang-catalog so you can give it a try:

`jbang ap-loader@maxandersen` for cli or `jbang --javaagent=ap-loader@maxandersen=....` to load as agent.

This can be combined with anything jbang can run, i.e.

`jbang --javaagent=ap-loader@maxandersen=start,event=cpu,file=profile.html quarkus@quarkusio` 

`jbang --javaagent=ap-loader@maxandersen=start,event=cpu,file=profile.html scriptondisk.java`

or ap-loader itself (except that fails because of multiple async-profilers collision)

`jbang --javaagent=ap-loader@maxandersen=start,event=cpu,file=profile.html me.bechberger:ap-loader-all:LATEST`

**Comment by parttimenerd** [comment]
> In that spirit I was wondering if you would be up for adding a jvm-profiling-tools/jbang-catalog github repo or adding a jbang-catalog.json to this repo ?

You could certainly create a PR to add this file (and write a notice in the README).
